apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointee-web
  labels:
    app: appointee-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointee-web
  template:
    metadata:
      labels:
        app: appointee-web
    spec:
      containers:
      - name: appointee-web
        image: registry.digitalocean.com/docr-appointee/web:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://appointee-api-service.default.svc.cluster.local
        - name: REACT_APP_GOOGLE_API_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: appointee-web-secrets
              key: ReactAppGoogleApiClientId
        - name: REACT_APP_GOOGLE_API_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: appointee-web-secrets
              key: ReactAppGoogleApiClientSecret
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: appointee-web-service
spec:
  selector:
    app: appointee-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
