name: AppointeeWeb

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:
    - name: Deploy to DigitalOcean Kubernetes
      run: |
        kubectl apply -f appoint-ee/website/deployment.yaml
