name: AppointeeWeb

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:
    - name: Deploy to DigitalOcean Kubernetes
      run: |
        ls
    - name: Deploy to DigitalOcean Kubernetes
      run: |
        pwd
    - name: Deploy to DigitalOcean Kubernetes
      run: |
        ls -lart
    - name: Deploy to DigitalOcean Kubernetes
      run: |
        kubectl apply -f .github/workflows/deployment.yaml
